### ISSUE TITLE
Merging tags: Too many similar tags used

### ISSUE THREAD

**Issue by neverything** [dol-lab/spaces-global-tags#21]
There are currently a lot of tags with only 1 or 2 posts assigned to it. Maybe it's too early to jump to any conclusion, but there seems to be an issue with the proposed tags.

![Screenshot 2019-11-06 09 56 24](https://user-images.githubusercontent.com/368120/68283513-f59e6f80-007b-11ea-8492-f47fc53eb4e3.png)

Let's explore some ideas on how to prevent this:

- Cache the tag response to make the suggestions faster
- Allow for tags to be merged, currently needs a manual update per post
- Ideas welcome...

**Comment by neverything** [comment]
In the call today with Monika we decided to only show the most used tags and show the number of usages so far. We will limit this list to approx. 30 tags that can be easily changed using a filter.

**Comment by mcschlatter** [comment]
Let's wait until more entries have tags in order to see if it's really a problem that some tags are similar (Wahrscheinlichkeitsräume is one topic in Wahrscheinlichkeitsrechnen. We will see if we need both or just the parent tag Wahrscheinlichkeitsrechnen) FE are now asked to add tags and we willhopefull soon see what happens ;-)

**Comment by neverything** [comment]
Add an all tags in taxonomy link so users actually find all tags on a single page.

**Comment by neverything** [comment]
Closing this for now @mcschlatter, can be reopened any time.
